pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'pwd && ls -ltr'
                sh 'cd cbr-as-provider && ls -ltr'
                echo 'Step Run'
                sh 'make build'
                sh 'ls -ltr'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing completed!'
            } 
        }
        stage('Run') {
            steps {
                echo 'Step Run'
                sh 'ls -ltr'
                sh './bin/cbr-as-provider/cbr-as-provider ${PARAM1}'
            }
        }
        stage('Completed') {
            steps {
               echo 'Task completed!'
            }
        }
    }
}