pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withCredentials([string(credentialsId: 'cbr_operator_service_zone_api_key_jj', variable: 'cbrServiceZoneApiKey')]) {
                    env.IBM_CLOUD_CBR_SERVICE_ZONE_API_KEY = cbrServiceZoneApiKey
                }
                echo 'Step Build'
                sh 'make build_service_zone_utils_cbr_as_provider'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing completed!'
            } 
        }
        stage('Run') {
            steps {
                echo 'Step Run'
                sh './bin/cbr-as-provider/cbr-as-provider ${PARAM1}' 
            }
        }
        stage('Completed') {
            steps {
               echo 'Task completed!'
            }
        }
    }
}